id: gtoc-upm
name: The Problem of the 12th Global Trajectory Optimisation Competition
competition_type: simple
awards_medals: false
prizes: null
description: mlebench/competitions/gtoc-upm/description.md

dataset:
  answers: gtoc-upm/prepared/public/GTOC12_Asteroids_Data.txt # dummy para evitar que detecte el dataset como no preparado
  sample_submission: gtoc-upm/prepared/public/GTOC12_Asteroids_Data.txt # dummy para evitar que detecte el dataset como no preparado

grader:
  name: accuracy
  grade_fn: mlebench.competitions.gtoc-upm.GTOC12_Verify.grade:grade

preparer: mlebench.competitions.gtoc-upm.prepare:prepare
